In [7]:
import torch
from torch.autograd import Variable


x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = Variable(torch.tensor([1.0]), requires_grad=True) # any random value
w

tensor([1.], requires_grad=True)

In [8]:

# our model forward pass
def forward(x):
    return x * w

# Loss function
def loss(y_pred, y_val):
    return (y_pred - y_val) ** 2

# Before training
print("Prediction (before training)",  4, forward(4).item())

# Training loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        y_pred = forward(x_val) # 1) Forward pass
        l = loss(y_pred, y_val) # 2) Compute loss
        l.backward() # 3) Back propagation to update weights
        print("\tgrad: ", x_val, y_val, w.grad.item())
        w.data = w.data - 0.01 * w.grad.item()

        # Manually zero the gradients after updating weights
        w.grad.data.zero_()

    print(f"Epoch: {epoch} | Loss: {l.item()}")

# After training
print("Prediction (after training)",  4, forward(4).item())

Prediction (before training) 4 4.0
	grad:  1.0 2.0 -2.0
	grad:  2.0 4.0 -7.840000152587891
	grad:  3.0 6.0 -16.228801727294922
Epoch: 0 | Loss: 7.315943717956543
	grad:  1.0 2.0 -1.478623867034912
	grad:  2.0 4.0 -5.796205520629883
	grad:  3.0 6.0 -11.998146057128906
Epoch: 1 | Loss: 3.9987640380859375
	grad:  1.0 2.0 -1.0931644439697266
	grad:  2.0 4.0 -4.285204887390137
	grad:  3.0 6.0 -8.870372772216797
Epoch: 2 | Loss: 2.1856532096862793
	grad:  1.0 2.0 -0.8081896305084229
	grad:  2.0 4.0 -3.1681032180786133
	grad:  3.0 6.0 -6.557973861694336
Epoch: 3 | Loss: 1.1946394443511963
	grad:  1.0 2.0 -0.5975041389465332
	grad:  2.0 4.0 -2.3422164916992188
	grad:  3.0 6.0 -4.848389625549316
Epoch: 4 | Loss: 0.6529689431190491
	grad:  1.0 2.0 -0.4417421817779541
	grad:  2.0 4.0 -1.7316293716430664
	grad:  3.0 6.0 -3.58447265625
Epoch: 5 | Loss: 0.35690122842788696
	grad:  1.0 2.0 -0.3265852928161621
	grad:  2.0 4.0 -1.2802143096923828
	grad:  3.0 6.0 -2.650045394897461
Epoch: 6 | Loss: 0.19

In [19]:
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        y_pred = forward(x_val) # 1) Forward pass
        l = loss(y_pred, y_val) # 2) Compute loss
        l.backward() # 3) Back propagation to update weights
        print(w.grad)
        print(w.grad.item())

tensor([-82.0546])
-82.05463409423828
tensor([-82.4449])
-82.44490814208984
tensor([-83.3230])
-83.3230209350586
tensor([-83.4206])
-83.42058563232422
tensor([-83.8109])
-83.81085968017578
tensor([-84.6890])
-84.68897247314453
tensor([-84.7865])
-84.78653717041016
tensor([-85.1768])
-85.17681121826172
tensor([-86.0549])
-86.05492401123047
tensor([-86.1525])
-86.1524887084961
tensor([-86.5428])
-86.54276275634766
tensor([-87.4209])
-87.4208755493164
tensor([-87.5184])
-87.51844024658203
tensor([-87.9087])
-87.9087142944336
tensor([-88.7868])
-88.78682708740234
tensor([-88.8844])
-88.88439178466797
tensor([-89.2747])
-89.27466583251953
tensor([-90.1528])
-90.15277862548828
tensor([-90.2503])
-90.2503433227539
tensor([-90.6406])
-90.64061737060547
tensor([-91.5187])
-91.51873016357422
tensor([-91.6163])
-91.61629486083984
tensor([-92.0066])
-92.0065689086914
tensor([-92.8847])
-92.88468170166016
tensor([-92.9822])
-92.98224639892578
tensor([-93.3725])
-93.37252044677734
tensor([-94.2506])